### PR TITLE
OSP-252: Update tox.ini on master, for python3

### PR DESCRIPTION
**Pull request by WeifanFu-bsn**
Reviewer: @sarath-kumar @wolverineav 

Codes look fine and need no update.

### CODE REVIEW

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_python_bsn_neutronclient_pull_req/19/

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_python_bsn_neutronclient_pull_req/20/

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_python_bsn_neutronclient_pull_req/21/

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_python_bsn_neutronclient_pull_req/22/

**Comment by wolverineav** [comment]
PR #15 is a clone of this PR. closing this and merging PR #15

**Pull request closed without merging**
